# Generated by Django 5.1.2 on 2024-10-16 11:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_review"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Review",
        ),
        migrations.DeleteModel(
            name="Task",
        ),
    ]
